#!/usr/bin/env python3
"""Sestavi custom_gear.xml pro Chummer: granaty (addweapon) + settingova munice.

Granaty jsou v Chummeru gear polozky kategorie "Ammunition", ktere pres
<addweapon> odkazuji na odpovidajici weapon entry v custom_weapons.xml.

Settingova munice: Tesla Charge Cell a Geist Munition (amunice pro settingove
zbrane). Bezna munice (ball, AP, hollow point, tracer, subsonic, incendiary)
se nepridava - SR5 ji uz obsahuje.

Pouziti: python3 build_gear_xml.py
"""
import csv, uuid, os
import xml.etree.ElementTree as ET

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "..", "..", "Chummer5a", "customdata", "ShadowWar 1938", "custom_gear.xml")
SOURCE = "SW1938"
GUID_NS = uuid.uuid5(uuid.NAMESPACE_URL, "shadowwar1938-gear")

BATCH9 = "batch09_tezke.tsv"

# settingova munice: (nazev, page, avail, cost, costfor, ammoforweapontype)
SPECIAL_AMMO = [
    ("Tesla Charge Cell", "102", "16F", "300", "6", "tesla"),
    ("Geist Munition", "105", "20F", "800", "4", "occult"),
]


def guid(name):
    return str(uuid.uuid5(GUID_NS, name))


def load_grenades():
    path = os.path.join(HERE, BATCH9)
    with open(path, encoding="utf-8") as f:
        reader = csv.reader(f, delimiter="\t")
        header = next(reader)
        out = []
        for line in reader:
            r = dict(zip(header, line))
            if r["SR5 kategorie"].strip() == "Gear":
                out.append(r)
    return out


def main():
    root = ET.Element("chummer")
    gears_el = ET.SubElement(root, "gears")

    def add(g, tag, val):
        if val is None:
            return
        val = str(val).strip()
        if val == "":
            return
        ET.SubElement(g, tag).text = val

    # granaty jako gear
    for r in load_grenades():
        name = r["Zbraň"].strip()
        g = ET.SubElement(gears_el, "gear")
        add(g, "id", guid(name))
        add(g, "name", name)
        add(g, "category", "Ammunition")
        add(g, "rating", "0")
        add(g, "source", SOURCE)
        add(g, "page", r["Číslo"])
        add(g, "avail", r["Avail"])
        add(g, "addweapon", name)
        add(g, "cost", r["Cost"])

    # settingova munice
    for name, page, avail, cost, costfor, ammofor in SPECIAL_AMMO:
        g = ET.SubElement(gears_el, "gear")
        add(g, "id", guid(name))
        add(g, "name", name)
        add(g, "category", "Ammunition")
        add(g, "rating", "0")
        add(g, "source", SOURCE)
        add(g, "page", page)
        add(g, "avail", avail)
        add(g, "cost", cost)
        add(g, "costfor", costfor)
        add(g, "ammoforweapontype", ammofor)

    header = (
        '<?xml version="1.0" encoding="utf-8"?>\n'
        "<!--\n"
        "  SHADOW WAR 1938 - custom gear (generated by build_gear_xml.py).\n"
        "  Grenades (addweapon) + special setting ammunition (Tesla/Geist).\n"
        "  Do not edit by hand.\n"
        "-->\n"
    )
    ET.indent(root, space="  ")
    with open(OUT, "w", encoding="utf-8") as f:
        f.write(header + ET.tostring(root, encoding="unicode") + "\n")

    n = len(root.find("gears"))
    print(f"Zapsano: {OUT}")
    print(f"Gear polozek: {n}")


if __name__ == "__main__":
    main()
