#!/usr/bin/env python3
"""Sestavi custom_gear.xml pro Chummer:
  - granaty (addweapon) z docs/weapons/batch09_tezke.tsv
  - obecne vybaveni z docs/gear/batchG1_vybaveni.tsv (vlastni kategorie SW1938)
  - settingova munice (Tesla Charge Cell, Geist Munition)

Bezna munice se nepridava (SR5 ji pokryva).

Pouziti: python3 build_gear_xml.py
"""
import csv, uuid, os
import xml.etree.ElementTree as ET

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.join(HERE, "..", "..")
OUT = os.path.join(ROOT, "Chummer5a", "customdata", "ShadowWar 1938", "custom_gear.xml")
SOURCE = "SW1938"
GUID_NS = uuid.uuid5(uuid.NAMESPACE_URL, "shadowwar1938-gear")

BATCH9 = os.path.join(HERE, "..", "weapons", "batch09_tezke.tsv")
GEAR_TSV = os.path.join(HERE, "batchG1_vybaveni.tsv")

# settingova munice: (nazev, page, avail, cost, costfor, ammoforweapontype)
SPECIAL_AMMO = [
    ("Tesla Charge Cell", "102", "16F", "300", "6", "tesla"),
    ("Geist Munition", "105", "20F", "800", "4", "occult"),
]

# blackmarket mapovani pro nase kategorie vybaveni
GEAR_BLACKMARKET = {
    "SW1938 – Elektronika": "Electronics",
    "SW1938 – Optika": "Electronics",
    "SW1938 – Zdravotnictví & chemie": "Drugs",
    "SW1938 – Nářadí & survival": "",
    "SW1938 – Okultní & teslapunk": "Magic",
    "SW1938 – Dokumenty & různé": "",
}


def guid(name):
    return str(uuid.uuid5(GUID_NS, name))


def read_tsv(path):
    with open(path, encoding="utf-8") as f:
        reader = csv.reader(f, delimiter="\t")
        header = next(reader)
        return [dict(zip(header, r)) for r in reader]


def main():
    root = ET.Element("chummer")

    # kategorie (jen pro obecne vybaveni; granaty a munice jedou pod Ammunition)
    gear_rows = read_tsv(GEAR_TSV)
    cats = sorted({r["SW1938 kategorie"].strip() for r in gear_rows})
    cats_el = ET.SubElement(root, "categories")
    for c in cats:
        attrs = {}
        bm = GEAR_BLACKMARKET.get(c, "")
        if bm:
            attrs["blackmarket"] = bm
        ET.SubElement(cats_el, "category", attrs).text = c

    gears_el = ET.SubElement(root, "gears")

    def add(g, tag, val):
        if val is None:
            return
        val = str(val).strip()
        if val == "" or val == "-":
            return
        ET.SubElement(g, tag).text = val

    # granaty jako gear (addweapon)
    for r in read_tsv(BATCH9):
        if r["SR5 kategorie"].strip() != "Gear":
            continue
        name = r["Zbraň"].strip()
        g = ET.SubElement(gears_el, "gear")
        add(g, "id", guid(name))
        add(g, "name", name)
        add(g, "category", "Ammunition")
        add(g, "rating", "0")
        add(g, "source", SOURCE)
        add(g, "page", r["Číslo"])
        add(g, "avail", r["Avail"])
        add(g, "addweapon", name)
        add(g, "cost", r["Cost"])

    # obecne vybaveni
    for r in gear_rows:
        name = r["Vybavení"].strip()
        g = ET.SubElement(gears_el, "gear")
        add(g, "id", guid(name))
        add(g, "name", name)
        add(g, "category", r["SW1938 kategorie"])
        add(g, "rating", r["Rating"] if r["Rating"].strip() else "0")
        add(g, "source", SOURCE)
        add(g, "page", r["Číslo"])
        add(g, "avail", r["Avail"])
        add(g, "cost", r["Cost"])
        add(g, "costfor", r["CostFor"])

    # settingova munice
    for name, page, avail, cost, costfor, ammofor in SPECIAL_AMMO:
        g = ET.SubElement(gears_el, "gear")
        add(g, "id", guid(name))
        add(g, "name", name)
        add(g, "category", "Ammunition")
        add(g, "rating", "0")
        add(g, "source", SOURCE)
        add(g, "page", page)
        add(g, "avail", avail)
        add(g, "cost", cost)
        add(g, "costfor", costfor)
        add(g, "ammoforweapontype", ammofor)

    header = (
        '<?xml version="1.0" encoding="utf-8"?>\n'
        "<!--\n"
        "  SHADOW WAR 1938 - custom gear (generated by build_gear_xml.py).\n"
        "  Grenades (addweapon) + general gear (SW1938 categories) + special ammo.\n"
        "  Do not edit by hand.\n"
        "-->\n"
    )
    ET.indent(root, space="  ")
    with open(OUT, "w", encoding="utf-8") as f:
        f.write(header + ET.tostring(root, encoding="unicode") + "\n")

    print(f"Zapsano: {OUT}")
    print(f"Gear polozek: {len(list(gears_el))} | kategorii vybaveni: {len(cats)}")


if __name__ == "__main__":
    main()
